//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Main/InputSettings/InputProfiler.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputProfiler : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputProfiler()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputProfiler"",
    ""maps"": [
        {
            ""name"": ""Profiler"",
            ""id"": ""f49beba3-b51d-4298-91c1-76778cf0afc4"",
            ""actions"": [
                {
                    ""name"": ""MoveKeys"",
                    ""type"": ""Button"",
                    ""id"": ""433e7d36-1d4a-4534-ac5f-90e04cb514fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d43905fb-ae74-4e5f-a571-2ef8f9a60faa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""100f2a91-9421-400a-a0f3-644c76d4072c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dd9e8aa9-7ea8-4488-97ff-862b16384ae1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveController"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e2ace138-0330-43c6-bba4-c2af5ffdc4c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""6e778ed4-7960-4d05-be51-839357fbd72e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""4240291d-bf7a-44e2-a3ed-6933b4203f42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Unarmed"",
                    ""type"": ""Button"",
                    ""id"": ""1c2afc73-6025-4260-97be-aea0c61445c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JetPack"",
                    ""type"": ""Button"",
                    ""id"": ""dc6a6fa0-90a0-4213-b617-3c464c14f180"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pollinate"",
                    ""type"": ""Button"",
                    ""id"": ""472b9a33-106c-4dff-9128-c6c5d861eebc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""EnableSkip"",
                    ""type"": ""Button"",
                    ""id"": ""c3a804c7-9da0-424b-b2eb-158a94d50e75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skip"",
                    ""type"": ""Button"",
                    ""id"": ""9053d697-3bcf-4b26-850c-a5636dc692d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TurnOnPhotoMode"",
                    ""type"": ""Button"",
                    ""id"": ""4628a971-7ce7-4940-aa99-8b8254946ffd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FieldDepthDown"",
                    ""type"": ""Button"",
                    ""id"": ""d733fd4d-baca-45f7-8830-3c624ef144ad"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FieldDepthUp"",
                    ""type"": ""Button"",
                    ""id"": ""e3210229-93ec-4251-9e8d-bc2958c46c9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TakePhoto"",
                    ""type"": ""Button"",
                    ""id"": ""89d930c5-3fae-47bc-a3a1-e4f687dec3c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""7ce4b6f2-3777-4a3c-98b2-c3cccf51e619"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AskMoonbeam"",
                    ""type"": ""Button"",
                    ""id"": ""ddd09c6b-dbc8-4bfc-b87e-6f71e761ce47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueOptionOne"",
                    ""type"": ""Button"",
                    ""id"": ""d4eb482d-3c77-466c-a30a-884dd7e02770"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueOptionTwo"",
                    ""type"": ""Button"",
                    ""id"": ""e1b888a9-49e9-4227-9191-9bbd435f9b49"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueOptionThree"",
                    ""type"": ""Button"",
                    ""id"": ""d6522fd3-519b-48a0-8e24-73dca8cb989a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""3b951d3c-7090-46db-a2e0-f3ba9de0f604"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StoreInteraction"",
                    ""type"": ""Button"",
                    ""id"": ""18e9d62c-414e-4b7a-9df0-b17a30c91170"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UpgradeCannon"",
                    ""type"": ""Button"",
                    ""id"": ""b44dd092-ad57-4631-bc18-65fd663e0dfe"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""OpenDungeon"",
                    ""type"": ""Button"",
                    ""id"": ""7da6b3d3-30bf-454c-815c-56d7eaa9557f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""805238ac-9544-4d8a-b9d3-dfef456d24ba"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6c7390f3-8675-42a0-a9be-fe20fa49dccd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b284b39f-3b40-47fd-a59c-8737b6ba6b3c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3743fd10-e77b-4872-8f30-3e7ee8c58136"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""881d10fe-0695-4ce1-94e2-40703ea34e7f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""155c5541-78b2-41e8-95da-1021d95e67f9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7afea426-7926-4a3c-a7ee-d46c5f458fdf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1ee3f5af-acd0-44dd-83a5-55997091482f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4cb723d9-c233-4128-8dba-f58e8fd6577c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ccf7c3e4-ee99-4290-bf3e-93d60771b6fb"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0448eba7-1b3c-4a14-80dc-c5ae8ee07d61"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e445b561-c31c-435f-b9a9-2a39f373eb04"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a84fe81c-ca6c-40f3-af79-7b1d5eec4a10"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ce0c4f8-7522-4a04-986f-db6ec03e37f8"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bc11560-f570-4ebe-b5ab-39e9f31b1126"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54dff0cd-19d0-4109-b9b8-a7f5ad922c43"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6848edb-09f0-4db7-b3c5-4f7eb43e2d8d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveController"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ad8b6db-b7a0-4e0e-8043-32059875d4aa"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45c8c501-058a-45ed-b3ef-7b8ba69df068"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11d48ce2-9caf-4a60-ae97-bd430866b06f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""903094cf-2fb4-4e34-b896-6f6543565a75"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f699abf-38ac-4de0-b11e-a6492f4118a5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unarmed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dce2e31-613e-4491-9dd6-69fc0f19c0a5"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unarmed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ffcee18-7828-4cf8-8362-7b9fb10ec970"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JetPack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fcd5292-d7ec-4a81-90f5-2890da45f076"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JetPack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cce6541b-739a-418a-a619-9a64e16ee9a0"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pollinate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3002d1b-8024-4954-a40b-84154aa09080"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pollinate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8f0df80-6ee5-4c70-be0a-a56c1efacfab"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a49e6dc5-996e-4184-9b29-3587332174e8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9381d58-dd4c-4f2c-8994-58e76a97de80"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84a63928-5e4b-4417-afab-6d0e88e83f26"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c1c8952-36a1-4770-9774-49dab52568d7"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""481fa344-97b9-41ed-ab5d-5047484eff88"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de35c756-dbd2-4afb-bcdb-9c4a747b7427"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e009e66-4aea-425a-91f1-e19aedb8b3e4"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78fd17da-4c0a-4acd-85cd-1cc6329bad8f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StoreInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""166b3d92-d287-4545-a235-e41a189588ea"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StoreInteraction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6abdae71-133e-43bb-91b3-c02d50e0a308"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpgradeCannon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7bb255c5-2ece-4cd3-a981-5706877df174"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UpgradeCannon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""747f54f8-af26-4fda-b334-452d82134dd1"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDungeon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""686146ae-7408-4e1c-98cd-fcf37307e2c1"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenDungeon"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c602c61-633d-4931-90a0-5ea9905f6fa7"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2eb89b7-5da0-45b9-9775-fe49162b5fa8"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eabb399e-c5b7-421e-a5b9-8e019bfeb2f7"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AskMoonbeam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a13734e-9ad8-4924-915b-d5f5872ef1b2"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AskMoonbeam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5261529-de21-4e99-aa67-3d6ad458ffa1"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed173062-3a2a-4a48-b974-4ecb2ba42099"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""68fef0a5-f1fd-42fc-bb9a-8729f12d7c7e"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnOnPhotoMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c177dae2-8a08-4885-bf73-ee66320fa920"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurnOnPhotoMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1e83e85a-062b-40d0-88bd-2112771385c1"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakePhoto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed635c93-2cca-42d6-ac72-773f91e77e58"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TakePhoto"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""98605d93-2a8b-413c-832b-052e2fa50015"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FieldDepthUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9249d95-ecc2-4cb7-bde0-6ec397aeb5eb"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FieldDepthUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""315794d7-ed29-4388-b0c7-c1acd56f775c"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FieldDepthDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1bee2da9-4947-44a8-8a35-97db472d0d14"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FieldDepthDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""390a0887-178b-47df-a184-42d9ae14173e"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableSkip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ac37b8ae-84b1-4363-946d-f15da4030561"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableSkip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b40d3d3f-e838-4163-bc86-3fdf8b6b80a6"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EnableSkip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InGameUI"",
            ""id"": ""ff290134-0d16-4aba-8456-7dec6d9f930e"",
            ""actions"": [
                {
                    ""name"": ""OpenLevelCompleteUI"",
                    ""type"": ""Button"",
                    ""id"": ""cd986be9-5696-4e33-b2ea-3fbd683e7c96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadMainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""59fcfca3-2793-4ebe-aec6-a0e264a2cd55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Resume"",
                    ""type"": ""Button"",
                    ""id"": ""92769aa7-bd09-46b7-92ee-00dc0883f0dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""Button"",
                    ""id"": ""0d7290e3-2e45-4890-a1cb-98fec5113871"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadNextPlanet"",
                    ""type"": ""Button"",
                    ""id"": ""c6f44670-9ad6-400c-b590-d7383c01fff6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiniMenu"",
                    ""type"": ""Button"",
                    ""id"": ""4cb82695-ff8b-4d06-9278-8c5e4eef1ed6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Controls"",
                    ""type"": ""Button"",
                    ""id"": ""47d5a112-a9a2-4079-b6eb-23d9f7b734a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BackBtn"",
                    ""type"": ""Button"",
                    ""id"": ""66181cf6-c60d-4814-a082-39c4c0ce2fb5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Keyboard"",
                    ""type"": ""Button"",
                    ""id"": ""c39670eb-76d8-426e-8e3a-5126c7af213f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayStation"",
                    ""type"": ""Button"",
                    ""id"": ""f5cabd3e-d77e-46e9-8ae6-5d7855669c0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Xbox"",
                    ""type"": ""Button"",
                    ""id"": ""38603cc5-57f7-443a-9b68-2c743b297b23"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""83812f27-0ff5-4724-b06f-48594200a6cd"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenLevelCompleteUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be804bf1-79d0-447b-aa7e-9f5c099ca487"",
                    ""path"": ""<Gamepad>/select"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenLevelCompleteUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9275bf79-c5ae-4f1c-b7f4-ab17205c2178"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextPlanet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f0eae27f-5112-460a-8230-4a4e6ec815fe"",
                    ""path"": ""<Keyboard>/n"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextPlanet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a41d8250-4df2-4cea-9379-f03f5924e98a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c26237d-f2fa-4826-8be0-23997c45d202"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8125e93-ecd0-4736-8dd3-56714afae38e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b28bf9e2-f1ad-4b24-9b3b-2aaa4aee8a4d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7710c767-b790-4a14-82a4-e6510480b742"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadMainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6883ac68-ff02-4769-b743-a30b619331c5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadMainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88a808d2-1e74-4508-a443-3f0145adf5dc"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiniMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64fba450-c2ae-4826-bd86-c3bd2da1b813"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiniMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b5ef65e-ce2d-48f4-bcdf-f191b9da4a08"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""57b12ab3-e638-4c65-8faf-99c31994cb86"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c6354e31-6096-4eb5-951d-7b6baa224ce2"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2f5b418-2e11-4474-8d95-619a81b89950"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BackBtn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fd98f22-4e27-4805-b0e2-877316713942"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Keyboard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""dcb1e818-29ce-4414-9afe-72b947f12f96"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayStation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""353e8574-0710-438b-a0e9-3f6058e3c695"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Xbox"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UIActions"",
            ""id"": ""94475e1e-50bd-40fb-84bb-a6e03404f335"",
            ""actions"": [
                {
                    ""name"": ""Mute"",
                    ""type"": ""Button"",
                    ""id"": ""98caf485-9edc-460e-839e-bf6da6aec2dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnMute"",
                    ""type"": ""Button"",
                    ""id"": ""34cda2b7-c41a-4ac7-9903-76d0485b58a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayCinematic"",
                    ""type"": ""Button"",
                    ""id"": ""447e6ff1-0c55-4154-845f-22acd7f8881a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3ba58c8a-e134-4c1b-b7bc-447d6a823f7a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbfdef33-8426-44af-a5a6-b8c6d4924016"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""098b02b6-bcf8-46c7-984f-572a3bbe2c14"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnMute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d90ded18-5796-4c1f-a019-ba4085359458"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnMute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66f3690e-94ed-479c-8097-368cde6a5a93"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayCinematic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7a619a7-85e8-4916-b330-8d437ade9649"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayCinematic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9bcd6afc-487f-45c9-8cd4-943a794bf25d"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayCinematic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""ControllerCursor"",
            ""id"": ""2018dd22-43b8-43f4-88b5-8537217e0db6"",
            ""actions"": [
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""ab4c849c-872e-4294-be04-24a35a67f042"",
                    ""expectedControlType"": ""Stick"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""22a5d3ad-0f18-42c8-b071-b82433c67eb5"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""Gamepad"",
            ""bindingGroup"": ""Gamepad"",
            ""devices"": [
                {
                    ""devicePath"": ""<Gamepad>"",
                    ""isOptional"": false,
                    ""isOR"": false
                },
                {
                    ""devicePath"": ""<VirtualMouse>"",
                    ""isOptional"": true,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Profiler
        m_Profiler = asset.FindActionMap("Profiler", throwIfNotFound: true);
        m_Profiler_MoveKeys = m_Profiler.FindAction("MoveKeys", throwIfNotFound: true);
        m_Profiler_Jump = m_Profiler.FindAction("Jump", throwIfNotFound: true);
        m_Profiler_Attack = m_Profiler.FindAction("Attack", throwIfNotFound: true);
        m_Profiler_Look = m_Profiler.FindAction("Look", throwIfNotFound: true);
        m_Profiler_MoveController = m_Profiler.FindAction("MoveController", throwIfNotFound: true);
        m_Profiler_Dodge = m_Profiler.FindAction("Dodge", throwIfNotFound: true);
        m_Profiler_Shoot = m_Profiler.FindAction("Shoot", throwIfNotFound: true);
        m_Profiler_Unarmed = m_Profiler.FindAction("Unarmed", throwIfNotFound: true);
        m_Profiler_JetPack = m_Profiler.FindAction("JetPack", throwIfNotFound: true);
        m_Profiler_Pollinate = m_Profiler.FindAction("Pollinate", throwIfNotFound: true);
        m_Profiler_EnableSkip = m_Profiler.FindAction("EnableSkip", throwIfNotFound: true);
        m_Profiler_Skip = m_Profiler.FindAction("Skip", throwIfNotFound: true);
        m_Profiler_TurnOnPhotoMode = m_Profiler.FindAction("TurnOnPhotoMode", throwIfNotFound: true);
        m_Profiler_FieldDepthDown = m_Profiler.FindAction("FieldDepthDown", throwIfNotFound: true);
        m_Profiler_FieldDepthUp = m_Profiler.FindAction("FieldDepthUp", throwIfNotFound: true);
        m_Profiler_TakePhoto = m_Profiler.FindAction("TakePhoto", throwIfNotFound: true);
        m_Profiler_ActivateDialogue = m_Profiler.FindAction("ActivateDialogue", throwIfNotFound: true);
        m_Profiler_AskMoonbeam = m_Profiler.FindAction("AskMoonbeam", throwIfNotFound: true);
        m_Profiler_DialogueOptionOne = m_Profiler.FindAction("DialogueOptionOne", throwIfNotFound: true);
        m_Profiler_DialogueOptionTwo = m_Profiler.FindAction("DialogueOptionTwo", throwIfNotFound: true);
        m_Profiler_DialogueOptionThree = m_Profiler.FindAction("DialogueOptionThree", throwIfNotFound: true);
        m_Profiler_CloseDialogue = m_Profiler.FindAction("CloseDialogue", throwIfNotFound: true);
        m_Profiler_StoreInteraction = m_Profiler.FindAction("StoreInteraction", throwIfNotFound: true);
        m_Profiler_UpgradeCannon = m_Profiler.FindAction("UpgradeCannon", throwIfNotFound: true);
        m_Profiler_OpenDungeon = m_Profiler.FindAction("OpenDungeon", throwIfNotFound: true);
        // InGameUI
        m_InGameUI = asset.FindActionMap("InGameUI", throwIfNotFound: true);
        m_InGameUI_OpenLevelCompleteUI = m_InGameUI.FindAction("OpenLevelCompleteUI", throwIfNotFound: true);
        m_InGameUI_LoadMainMenu = m_InGameUI.FindAction("LoadMainMenu", throwIfNotFound: true);
        m_InGameUI_Resume = m_InGameUI.FindAction("Resume", throwIfNotFound: true);
        m_InGameUI_PauseGame = m_InGameUI.FindAction("PauseGame", throwIfNotFound: true);
        m_InGameUI_LoadNextPlanet = m_InGameUI.FindAction("LoadNextPlanet", throwIfNotFound: true);
        m_InGameUI_MiniMenu = m_InGameUI.FindAction("MiniMenu", throwIfNotFound: true);
        m_InGameUI_Controls = m_InGameUI.FindAction("Controls", throwIfNotFound: true);
        m_InGameUI_BackBtn = m_InGameUI.FindAction("BackBtn", throwIfNotFound: true);
        m_InGameUI_Keyboard = m_InGameUI.FindAction("Keyboard", throwIfNotFound: true);
        m_InGameUI_PlayStation = m_InGameUI.FindAction("PlayStation", throwIfNotFound: true);
        m_InGameUI_Xbox = m_InGameUI.FindAction("Xbox", throwIfNotFound: true);
        // UIActions
        m_UIActions = asset.FindActionMap("UIActions", throwIfNotFound: true);
        m_UIActions_Mute = m_UIActions.FindAction("Mute", throwIfNotFound: true);
        m_UIActions_UnMute = m_UIActions.FindAction("UnMute", throwIfNotFound: true);
        m_UIActions_PlayCinematic = m_UIActions.FindAction("PlayCinematic", throwIfNotFound: true);
        // ControllerCursor
        m_ControllerCursor = asset.FindActionMap("ControllerCursor", throwIfNotFound: true);
        m_ControllerCursor_Move = m_ControllerCursor.FindAction("Move", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Profiler
    private readonly InputActionMap m_Profiler;
    private IProfilerActions m_ProfilerActionsCallbackInterface;
    private readonly InputAction m_Profiler_MoveKeys;
    private readonly InputAction m_Profiler_Jump;
    private readonly InputAction m_Profiler_Attack;
    private readonly InputAction m_Profiler_Look;
    private readonly InputAction m_Profiler_MoveController;
    private readonly InputAction m_Profiler_Dodge;
    private readonly InputAction m_Profiler_Shoot;
    private readonly InputAction m_Profiler_Unarmed;
    private readonly InputAction m_Profiler_JetPack;
    private readonly InputAction m_Profiler_Pollinate;
    private readonly InputAction m_Profiler_EnableSkip;
    private readonly InputAction m_Profiler_Skip;
    private readonly InputAction m_Profiler_TurnOnPhotoMode;
    private readonly InputAction m_Profiler_FieldDepthDown;
    private readonly InputAction m_Profiler_FieldDepthUp;
    private readonly InputAction m_Profiler_TakePhoto;
    private readonly InputAction m_Profiler_ActivateDialogue;
    private readonly InputAction m_Profiler_AskMoonbeam;
    private readonly InputAction m_Profiler_DialogueOptionOne;
    private readonly InputAction m_Profiler_DialogueOptionTwo;
    private readonly InputAction m_Profiler_DialogueOptionThree;
    private readonly InputAction m_Profiler_CloseDialogue;
    private readonly InputAction m_Profiler_StoreInteraction;
    private readonly InputAction m_Profiler_UpgradeCannon;
    private readonly InputAction m_Profiler_OpenDungeon;
    public struct ProfilerActions
    {
        private @InputProfiler m_Wrapper;
        public ProfilerActions(@InputProfiler wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveKeys => m_Wrapper.m_Profiler_MoveKeys;
        public InputAction @Jump => m_Wrapper.m_Profiler_Jump;
        public InputAction @Attack => m_Wrapper.m_Profiler_Attack;
        public InputAction @Look => m_Wrapper.m_Profiler_Look;
        public InputAction @MoveController => m_Wrapper.m_Profiler_MoveController;
        public InputAction @Dodge => m_Wrapper.m_Profiler_Dodge;
        public InputAction @Shoot => m_Wrapper.m_Profiler_Shoot;
        public InputAction @Unarmed => m_Wrapper.m_Profiler_Unarmed;
        public InputAction @JetPack => m_Wrapper.m_Profiler_JetPack;
        public InputAction @Pollinate => m_Wrapper.m_Profiler_Pollinate;
        public InputAction @EnableSkip => m_Wrapper.m_Profiler_EnableSkip;
        public InputAction @Skip => m_Wrapper.m_Profiler_Skip;
        public InputAction @TurnOnPhotoMode => m_Wrapper.m_Profiler_TurnOnPhotoMode;
        public InputAction @FieldDepthDown => m_Wrapper.m_Profiler_FieldDepthDown;
        public InputAction @FieldDepthUp => m_Wrapper.m_Profiler_FieldDepthUp;
        public InputAction @TakePhoto => m_Wrapper.m_Profiler_TakePhoto;
        public InputAction @ActivateDialogue => m_Wrapper.m_Profiler_ActivateDialogue;
        public InputAction @AskMoonbeam => m_Wrapper.m_Profiler_AskMoonbeam;
        public InputAction @DialogueOptionOne => m_Wrapper.m_Profiler_DialogueOptionOne;
        public InputAction @DialogueOptionTwo => m_Wrapper.m_Profiler_DialogueOptionTwo;
        public InputAction @DialogueOptionThree => m_Wrapper.m_Profiler_DialogueOptionThree;
        public InputAction @CloseDialogue => m_Wrapper.m_Profiler_CloseDialogue;
        public InputAction @StoreInteraction => m_Wrapper.m_Profiler_StoreInteraction;
        public InputAction @UpgradeCannon => m_Wrapper.m_Profiler_UpgradeCannon;
        public InputAction @OpenDungeon => m_Wrapper.m_Profiler_OpenDungeon;
        public InputActionMap Get() { return m_Wrapper.m_Profiler; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ProfilerActions set) { return set.Get(); }
        public void SetCallbacks(IProfilerActions instance)
        {
            if (m_Wrapper.m_ProfilerActionsCallbackInterface != null)
            {
                @MoveKeys.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveKeys;
                @MoveKeys.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveKeys;
                @MoveKeys.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveKeys;
                @Jump.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJump;
                @Attack.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAttack;
                @Look.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnLook;
                @MoveController.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveController;
                @MoveController.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveController;
                @MoveController.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveController;
                @Dodge.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDodge;
                @Dodge.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDodge;
                @Dodge.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDodge;
                @Shoot.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnShoot;
                @Unarmed.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUnarmed;
                @Unarmed.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUnarmed;
                @Unarmed.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUnarmed;
                @JetPack.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJetPack;
                @JetPack.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJetPack;
                @JetPack.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJetPack;
                @Pollinate.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnPollinate;
                @Pollinate.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnPollinate;
                @Pollinate.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnPollinate;
                @EnableSkip.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnEnableSkip;
                @EnableSkip.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnEnableSkip;
                @EnableSkip.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnEnableSkip;
                @Skip.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnSkip;
                @Skip.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnSkip;
                @Skip.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnSkip;
                @TurnOnPhotoMode.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTurnOnPhotoMode;
                @TurnOnPhotoMode.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTurnOnPhotoMode;
                @TurnOnPhotoMode.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTurnOnPhotoMode;
                @FieldDepthDown.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnFieldDepthDown;
                @FieldDepthDown.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnFieldDepthDown;
                @FieldDepthDown.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnFieldDepthDown;
                @FieldDepthUp.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnFieldDepthUp;
                @FieldDepthUp.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnFieldDepthUp;
                @FieldDepthUp.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnFieldDepthUp;
                @TakePhoto.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTakePhoto;
                @TakePhoto.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTakePhoto;
                @TakePhoto.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTakePhoto;
                @ActivateDialogue.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnActivateDialogue;
                @ActivateDialogue.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnActivateDialogue;
                @ActivateDialogue.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnActivateDialogue;
                @AskMoonbeam.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAskMoonbeam;
                @AskMoonbeam.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAskMoonbeam;
                @AskMoonbeam.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAskMoonbeam;
                @DialogueOptionOne.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionOne;
                @DialogueOptionOne.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionOne;
                @DialogueOptionOne.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionOne;
                @DialogueOptionTwo.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionTwo;
                @DialogueOptionTwo.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionTwo;
                @DialogueOptionTwo.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionTwo;
                @DialogueOptionThree.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionThree;
                @DialogueOptionThree.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionThree;
                @DialogueOptionThree.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionThree;
                @CloseDialogue.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnCloseDialogue;
                @CloseDialogue.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnCloseDialogue;
                @CloseDialogue.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnCloseDialogue;
                @StoreInteraction.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnStoreInteraction;
                @StoreInteraction.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnStoreInteraction;
                @StoreInteraction.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnStoreInteraction;
                @UpgradeCannon.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUpgradeCannon;
                @UpgradeCannon.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUpgradeCannon;
                @UpgradeCannon.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUpgradeCannon;
                @OpenDungeon.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnOpenDungeon;
                @OpenDungeon.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnOpenDungeon;
                @OpenDungeon.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnOpenDungeon;
            }
            m_Wrapper.m_ProfilerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveKeys.started += instance.OnMoveKeys;
                @MoveKeys.performed += instance.OnMoveKeys;
                @MoveKeys.canceled += instance.OnMoveKeys;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @MoveController.started += instance.OnMoveController;
                @MoveController.performed += instance.OnMoveController;
                @MoveController.canceled += instance.OnMoveController;
                @Dodge.started += instance.OnDodge;
                @Dodge.performed += instance.OnDodge;
                @Dodge.canceled += instance.OnDodge;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Unarmed.started += instance.OnUnarmed;
                @Unarmed.performed += instance.OnUnarmed;
                @Unarmed.canceled += instance.OnUnarmed;
                @JetPack.started += instance.OnJetPack;
                @JetPack.performed += instance.OnJetPack;
                @JetPack.canceled += instance.OnJetPack;
                @Pollinate.started += instance.OnPollinate;
                @Pollinate.performed += instance.OnPollinate;
                @Pollinate.canceled += instance.OnPollinate;
                @EnableSkip.started += instance.OnEnableSkip;
                @EnableSkip.performed += instance.OnEnableSkip;
                @EnableSkip.canceled += instance.OnEnableSkip;
                @Skip.started += instance.OnSkip;
                @Skip.performed += instance.OnSkip;
                @Skip.canceled += instance.OnSkip;
                @TurnOnPhotoMode.started += instance.OnTurnOnPhotoMode;
                @TurnOnPhotoMode.performed += instance.OnTurnOnPhotoMode;
                @TurnOnPhotoMode.canceled += instance.OnTurnOnPhotoMode;
                @FieldDepthDown.started += instance.OnFieldDepthDown;
                @FieldDepthDown.performed += instance.OnFieldDepthDown;
                @FieldDepthDown.canceled += instance.OnFieldDepthDown;
                @FieldDepthUp.started += instance.OnFieldDepthUp;
                @FieldDepthUp.performed += instance.OnFieldDepthUp;
                @FieldDepthUp.canceled += instance.OnFieldDepthUp;
                @TakePhoto.started += instance.OnTakePhoto;
                @TakePhoto.performed += instance.OnTakePhoto;
                @TakePhoto.canceled += instance.OnTakePhoto;
                @ActivateDialogue.started += instance.OnActivateDialogue;
                @ActivateDialogue.performed += instance.OnActivateDialogue;
                @ActivateDialogue.canceled += instance.OnActivateDialogue;
                @AskMoonbeam.started += instance.OnAskMoonbeam;
                @AskMoonbeam.performed += instance.OnAskMoonbeam;
                @AskMoonbeam.canceled += instance.OnAskMoonbeam;
                @DialogueOptionOne.started += instance.OnDialogueOptionOne;
                @DialogueOptionOne.performed += instance.OnDialogueOptionOne;
                @DialogueOptionOne.canceled += instance.OnDialogueOptionOne;
                @DialogueOptionTwo.started += instance.OnDialogueOptionTwo;
                @DialogueOptionTwo.performed += instance.OnDialogueOptionTwo;
                @DialogueOptionTwo.canceled += instance.OnDialogueOptionTwo;
                @DialogueOptionThree.started += instance.OnDialogueOptionThree;
                @DialogueOptionThree.performed += instance.OnDialogueOptionThree;
                @DialogueOptionThree.canceled += instance.OnDialogueOptionThree;
                @CloseDialogue.started += instance.OnCloseDialogue;
                @CloseDialogue.performed += instance.OnCloseDialogue;
                @CloseDialogue.canceled += instance.OnCloseDialogue;
                @StoreInteraction.started += instance.OnStoreInteraction;
                @StoreInteraction.performed += instance.OnStoreInteraction;
                @StoreInteraction.canceled += instance.OnStoreInteraction;
                @UpgradeCannon.started += instance.OnUpgradeCannon;
                @UpgradeCannon.performed += instance.OnUpgradeCannon;
                @UpgradeCannon.canceled += instance.OnUpgradeCannon;
                @OpenDungeon.started += instance.OnOpenDungeon;
                @OpenDungeon.performed += instance.OnOpenDungeon;
                @OpenDungeon.canceled += instance.OnOpenDungeon;
            }
        }
    }
    public ProfilerActions @Profiler => new ProfilerActions(this);

    // InGameUI
    private readonly InputActionMap m_InGameUI;
    private IInGameUIActions m_InGameUIActionsCallbackInterface;
    private readonly InputAction m_InGameUI_OpenLevelCompleteUI;
    private readonly InputAction m_InGameUI_LoadMainMenu;
    private readonly InputAction m_InGameUI_Resume;
    private readonly InputAction m_InGameUI_PauseGame;
    private readonly InputAction m_InGameUI_LoadNextPlanet;
    private readonly InputAction m_InGameUI_MiniMenu;
    private readonly InputAction m_InGameUI_Controls;
    private readonly InputAction m_InGameUI_BackBtn;
    private readonly InputAction m_InGameUI_Keyboard;
    private readonly InputAction m_InGameUI_PlayStation;
    private readonly InputAction m_InGameUI_Xbox;
    public struct InGameUIActions
    {
        private @InputProfiler m_Wrapper;
        public InGameUIActions(@InputProfiler wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenLevelCompleteUI => m_Wrapper.m_InGameUI_OpenLevelCompleteUI;
        public InputAction @LoadMainMenu => m_Wrapper.m_InGameUI_LoadMainMenu;
        public InputAction @Resume => m_Wrapper.m_InGameUI_Resume;
        public InputAction @PauseGame => m_Wrapper.m_InGameUI_PauseGame;
        public InputAction @LoadNextPlanet => m_Wrapper.m_InGameUI_LoadNextPlanet;
        public InputAction @MiniMenu => m_Wrapper.m_InGameUI_MiniMenu;
        public InputAction @Controls => m_Wrapper.m_InGameUI_Controls;
        public InputAction @BackBtn => m_Wrapper.m_InGameUI_BackBtn;
        public InputAction @Keyboard => m_Wrapper.m_InGameUI_Keyboard;
        public InputAction @PlayStation => m_Wrapper.m_InGameUI_PlayStation;
        public InputAction @Xbox => m_Wrapper.m_InGameUI_Xbox;
        public InputActionMap Get() { return m_Wrapper.m_InGameUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameUIActions set) { return set.Get(); }
        public void SetCallbacks(IInGameUIActions instance)
        {
            if (m_Wrapper.m_InGameUIActionsCallbackInterface != null)
            {
                @OpenLevelCompleteUI.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnOpenLevelCompleteUI;
                @OpenLevelCompleteUI.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnOpenLevelCompleteUI;
                @OpenLevelCompleteUI.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnOpenLevelCompleteUI;
                @LoadMainMenu.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadMainMenu;
                @LoadMainMenu.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadMainMenu;
                @LoadMainMenu.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadMainMenu;
                @Resume.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnResume;
                @Resume.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnResume;
                @Resume.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnResume;
                @PauseGame.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPauseGame;
                @LoadNextPlanet.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadNextPlanet;
                @LoadNextPlanet.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadNextPlanet;
                @LoadNextPlanet.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadNextPlanet;
                @MiniMenu.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnMiniMenu;
                @MiniMenu.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnMiniMenu;
                @MiniMenu.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnMiniMenu;
                @Controls.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnControls;
                @Controls.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnControls;
                @Controls.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnControls;
                @BackBtn.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnBackBtn;
                @BackBtn.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnBackBtn;
                @BackBtn.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnBackBtn;
                @Keyboard.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnKeyboard;
                @Keyboard.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnKeyboard;
                @Keyboard.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnKeyboard;
                @PlayStation.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPlayStation;
                @PlayStation.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPlayStation;
                @PlayStation.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPlayStation;
                @Xbox.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnXbox;
                @Xbox.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnXbox;
                @Xbox.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnXbox;
            }
            m_Wrapper.m_InGameUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenLevelCompleteUI.started += instance.OnOpenLevelCompleteUI;
                @OpenLevelCompleteUI.performed += instance.OnOpenLevelCompleteUI;
                @OpenLevelCompleteUI.canceled += instance.OnOpenLevelCompleteUI;
                @LoadMainMenu.started += instance.OnLoadMainMenu;
                @LoadMainMenu.performed += instance.OnLoadMainMenu;
                @LoadMainMenu.canceled += instance.OnLoadMainMenu;
                @Resume.started += instance.OnResume;
                @Resume.performed += instance.OnResume;
                @Resume.canceled += instance.OnResume;
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
                @LoadNextPlanet.started += instance.OnLoadNextPlanet;
                @LoadNextPlanet.performed += instance.OnLoadNextPlanet;
                @LoadNextPlanet.canceled += instance.OnLoadNextPlanet;
                @MiniMenu.started += instance.OnMiniMenu;
                @MiniMenu.performed += instance.OnMiniMenu;
                @MiniMenu.canceled += instance.OnMiniMenu;
                @Controls.started += instance.OnControls;
                @Controls.performed += instance.OnControls;
                @Controls.canceled += instance.OnControls;
                @BackBtn.started += instance.OnBackBtn;
                @BackBtn.performed += instance.OnBackBtn;
                @BackBtn.canceled += instance.OnBackBtn;
                @Keyboard.started += instance.OnKeyboard;
                @Keyboard.performed += instance.OnKeyboard;
                @Keyboard.canceled += instance.OnKeyboard;
                @PlayStation.started += instance.OnPlayStation;
                @PlayStation.performed += instance.OnPlayStation;
                @PlayStation.canceled += instance.OnPlayStation;
                @Xbox.started += instance.OnXbox;
                @Xbox.performed += instance.OnXbox;
                @Xbox.canceled += instance.OnXbox;
            }
        }
    }
    public InGameUIActions @InGameUI => new InGameUIActions(this);

    // UIActions
    private readonly InputActionMap m_UIActions;
    private IUIActionsActions m_UIActionsActionsCallbackInterface;
    private readonly InputAction m_UIActions_Mute;
    private readonly InputAction m_UIActions_UnMute;
    private readonly InputAction m_UIActions_PlayCinematic;
    public struct UIActionsActions
    {
        private @InputProfiler m_Wrapper;
        public UIActionsActions(@InputProfiler wrapper) { m_Wrapper = wrapper; }
        public InputAction @Mute => m_Wrapper.m_UIActions_Mute;
        public InputAction @UnMute => m_Wrapper.m_UIActions_UnMute;
        public InputAction @PlayCinematic => m_Wrapper.m_UIActions_PlayCinematic;
        public InputActionMap Get() { return m_Wrapper.m_UIActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActionsActions set) { return set.Get(); }
        public void SetCallbacks(IUIActionsActions instance)
        {
            if (m_Wrapper.m_UIActionsActionsCallbackInterface != null)
            {
                @Mute.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnMute;
                @Mute.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnMute;
                @Mute.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnMute;
                @UnMute.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnUnMute;
                @UnMute.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnUnMute;
                @UnMute.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnUnMute;
                @PlayCinematic.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayCinematic;
                @PlayCinematic.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayCinematic;
                @PlayCinematic.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayCinematic;
            }
            m_Wrapper.m_UIActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Mute.started += instance.OnMute;
                @Mute.performed += instance.OnMute;
                @Mute.canceled += instance.OnMute;
                @UnMute.started += instance.OnUnMute;
                @UnMute.performed += instance.OnUnMute;
                @UnMute.canceled += instance.OnUnMute;
                @PlayCinematic.started += instance.OnPlayCinematic;
                @PlayCinematic.performed += instance.OnPlayCinematic;
                @PlayCinematic.canceled += instance.OnPlayCinematic;
            }
        }
    }
    public UIActionsActions @UIActions => new UIActionsActions(this);

    // ControllerCursor
    private readonly InputActionMap m_ControllerCursor;
    private IControllerCursorActions m_ControllerCursorActionsCallbackInterface;
    private readonly InputAction m_ControllerCursor_Move;
    public struct ControllerCursorActions
    {
        private @InputProfiler m_Wrapper;
        public ControllerCursorActions(@InputProfiler wrapper) { m_Wrapper = wrapper; }
        public InputAction @Move => m_Wrapper.m_ControllerCursor_Move;
        public InputActionMap Get() { return m_Wrapper.m_ControllerCursor; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ControllerCursorActions set) { return set.Get(); }
        public void SetCallbacks(IControllerCursorActions instance)
        {
            if (m_Wrapper.m_ControllerCursorActionsCallbackInterface != null)
            {
                @Move.started -= m_Wrapper.m_ControllerCursorActionsCallbackInterface.OnMove;
                @Move.performed -= m_Wrapper.m_ControllerCursorActionsCallbackInterface.OnMove;
                @Move.canceled -= m_Wrapper.m_ControllerCursorActionsCallbackInterface.OnMove;
            }
            m_Wrapper.m_ControllerCursorActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Move.started += instance.OnMove;
                @Move.performed += instance.OnMove;
                @Move.canceled += instance.OnMove;
            }
        }
    }
    public ControllerCursorActions @ControllerCursor => new ControllerCursorActions(this);
    private int m_GamepadSchemeIndex = -1;
    public InputControlScheme GamepadScheme
    {
        get
        {
            if (m_GamepadSchemeIndex == -1) m_GamepadSchemeIndex = asset.FindControlSchemeIndex("Gamepad");
            return asset.controlSchemes[m_GamepadSchemeIndex];
        }
    }
    public interface IProfilerActions
    {
        void OnMoveKeys(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnMoveController(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnUnarmed(InputAction.CallbackContext context);
        void OnJetPack(InputAction.CallbackContext context);
        void OnPollinate(InputAction.CallbackContext context);
        void OnEnableSkip(InputAction.CallbackContext context);
        void OnSkip(InputAction.CallbackContext context);
        void OnTurnOnPhotoMode(InputAction.CallbackContext context);
        void OnFieldDepthDown(InputAction.CallbackContext context);
        void OnFieldDepthUp(InputAction.CallbackContext context);
        void OnTakePhoto(InputAction.CallbackContext context);
        void OnActivateDialogue(InputAction.CallbackContext context);
        void OnAskMoonbeam(InputAction.CallbackContext context);
        void OnDialogueOptionOne(InputAction.CallbackContext context);
        void OnDialogueOptionTwo(InputAction.CallbackContext context);
        void OnDialogueOptionThree(InputAction.CallbackContext context);
        void OnCloseDialogue(InputAction.CallbackContext context);
        void OnStoreInteraction(InputAction.CallbackContext context);
        void OnUpgradeCannon(InputAction.CallbackContext context);
        void OnOpenDungeon(InputAction.CallbackContext context);
    }
    public interface IInGameUIActions
    {
        void OnOpenLevelCompleteUI(InputAction.CallbackContext context);
        void OnLoadMainMenu(InputAction.CallbackContext context);
        void OnResume(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnLoadNextPlanet(InputAction.CallbackContext context);
        void OnMiniMenu(InputAction.CallbackContext context);
        void OnControls(InputAction.CallbackContext context);
        void OnBackBtn(InputAction.CallbackContext context);
        void OnKeyboard(InputAction.CallbackContext context);
        void OnPlayStation(InputAction.CallbackContext context);
        void OnXbox(InputAction.CallbackContext context);
    }
    public interface IUIActionsActions
    {
        void OnMute(InputAction.CallbackContext context);
        void OnUnMute(InputAction.CallbackContext context);
        void OnPlayCinematic(InputAction.CallbackContext context);
    }
    public interface IControllerCursorActions
    {
        void OnMove(InputAction.CallbackContext context);
    }
}
