//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Main/InputSettings/InputProfiler.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @InputProfiler : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @InputProfiler()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""InputProfiler"",
    ""maps"": [
        {
            ""name"": ""Profiler"",
            ""id"": ""f49beba3-b51d-4298-91c1-76778cf0afc4"",
            ""actions"": [
                {
                    ""name"": ""MoveKeys"",
                    ""type"": ""Button"",
                    ""id"": ""433e7d36-1d4a-4534-ac5f-90e04cb514fa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""d43905fb-ae74-4e5f-a571-2ef8f9a60faa"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Attack"",
                    ""type"": ""Button"",
                    ""id"": ""100f2a91-9421-400a-a0f3-644c76d4072c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dd9e8aa9-7ea8-4488-97ff-862b16384ae1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MoveController"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e2ace138-0330-43c6-bba4-c2af5ffdc4c7"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Dodge"",
                    ""type"": ""Button"",
                    ""id"": ""6e778ed4-7960-4d05-be51-839357fbd72e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""4240291d-bf7a-44e2-a3ed-6933b4203f42"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Unarmed"",
                    ""type"": ""Button"",
                    ""id"": ""1c2afc73-6025-4260-97be-aea0c61445c6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Skip"",
                    ""type"": ""Button"",
                    ""id"": ""9053d697-3bcf-4b26-850c-a5636dc692d3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""JetPack"",
                    ""type"": ""Button"",
                    ""id"": ""dc6a6fa0-90a0-4213-b617-3c464c14f180"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TalkArgyle"",
                    ""type"": ""Button"",
                    ""id"": ""18e9d62c-414e-4b7a-9df0-b17a30c91170"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pollinate"",
                    ""type"": ""Button"",
                    ""id"": ""472b9a33-106c-4dff-9128-c6c5d861eebc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueOptionOne"",
                    ""type"": ""Button"",
                    ""id"": ""d4eb482d-3c77-466c-a30a-884dd7e02770"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueOptionTwo"",
                    ""type"": ""Button"",
                    ""id"": ""e1b888a9-49e9-4227-9191-9bbd435f9b49"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""DialogueOptionThree"",
                    ""type"": ""Button"",
                    ""id"": ""d6522fd3-519b-48a0-8e24-73dca8cb989a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ActivateDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""7ce4b6f2-3777-4a3c-98b2-c3cccf51e619"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""AskMoonbeam"",
                    ""type"": ""Button"",
                    ""id"": ""ddd09c6b-dbc8-4bfc-b87e-6f71e761ce47"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""CloseDialogue"",
                    ""type"": ""Button"",
                    ""id"": ""3b951d3c-7090-46db-a2e0-f3ba9de0f604"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""WASD"",
                    ""id"": ""805238ac-9544-4d8a-b9d3-dfef456d24ba"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""6c7390f3-8675-42a0-a9be-fe20fa49dccd"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""b284b39f-3b40-47fd-a59c-8737b6ba6b3c"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""3743fd10-e77b-4872-8f30-3e7ee8c58136"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""881d10fe-0695-4ce1-94e2-40703ea34e7f"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""155c5541-78b2-41e8-95da-1021d95e67f9"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""7afea426-7926-4a3c-a7ee-d46c5f458fdf"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""1ee3f5af-acd0-44dd-83a5-55997091482f"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""4cb723d9-c233-4128-8dba-f58e8fd6577c"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ccf7c3e4-ee99-4290-bf3e-93d60771b6fb"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveKeys"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""0448eba7-1b3c-4a14-80dc-c5ae8ee07d61"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e445b561-c31c-435f-b9a9-2a39f373eb04"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a84fe81c-ca6c-40f3-af79-7b1d5eec4a10"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ce0c4f8-7522-4a04-986f-db6ec03e37f8"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Attack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4bc11560-f570-4ebe-b5ab-39e9f31b1126"",
                    ""path"": ""<Mouse>/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""54dff0cd-19d0-4109-b9b8-a7f5ad922c43"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a6848edb-09f0-4db7-b3c5-4f7eb43e2d8d"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveController"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6ad8b6db-b7a0-4e0e-8043-32059875d4aa"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""45c8c501-058a-45ed-b3ef-7b8ba69df068"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Dodge"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""11d48ce2-9caf-4a60-ae97-bd430866b06f"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""903094cf-2fb4-4e34-b896-6f6543565a75"",
                    ""path"": ""<Mouse>/rightButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f699abf-38ac-4de0-b11e-a6492f4118a5"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unarmed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5dce2e31-613e-4491-9dd6-69fc0f19c0a5"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Unarmed"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c5261529-de21-4e99-aa67-3d6ad458ffa1"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed173062-3a2a-4a48-b974-4ecb2ba42099"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Skip"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""2ffcee18-7828-4cf8-8362-7b9fb10ec970"",
                    ""path"": ""<Keyboard>/shift"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JetPack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5fcd5292-d7ec-4a81-90f5-2890da45f076"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""JetPack"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""78fd17da-4c0a-4acd-85cd-1cc6329bad8f"",
                    ""path"": ""<Keyboard>/f"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TalkArgyle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""166b3d92-d287-4545-a235-e41a189588ea"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TalkArgyle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cce6541b-739a-418a-a619-9a64e16ee9a0"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pollinate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e3002d1b-8024-4954-a40b-84154aa09080"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pollinate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8f0df80-6ee5-4c70-be0a-a56c1efacfab"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a49e6dc5-996e-4184-9b29-3587332174e8"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionOne"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a9381d58-dd4c-4f2c-8994-58e76a97de80"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""84a63928-5e4b-4417-afab-6d0e88e83f26"",
                    ""path"": ""<Gamepad>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionTwo"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1c1c8952-36a1-4770-9774-49dab52568d7"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""481fa344-97b9-41ed-ab5d-5047484eff88"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""DialogueOptionThree"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3c602c61-633d-4931-90a0-5ea9905f6fa7"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a2eb89b7-5da0-45b9-9775-fe49162b5fa8"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ActivateDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""eabb399e-c5b7-421e-a5b9-8e019bfeb2f7"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AskMoonbeam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a13734e-9ad8-4924-915b-d5f5872ef1b2"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""AskMoonbeam"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""de35c756-dbd2-4afb-bcdb-9c4a747b7427"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6e009e66-4aea-425a-91f1-e19aedb8b3e4"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""CloseDialogue"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InGameUI"",
            ""id"": ""ff290134-0d16-4aba-8456-7dec6d9f930e"",
            ""actions"": [
                {
                    ""name"": ""OpenLevelCompleteUI"",
                    ""type"": ""Button"",
                    ""id"": ""cd986be9-5696-4e33-b2ea-3fbd683e7c96"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadMainMenu"",
                    ""type"": ""Button"",
                    ""id"": ""59fcfca3-2793-4ebe-aec6-a0e264a2cd55"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Resume"",
                    ""type"": ""Button"",
                    ""id"": ""92769aa7-bd09-46b7-92ee-00dc0883f0dc"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""Button"",
                    ""id"": ""0d7290e3-2e45-4890-a1cb-98fec5113871"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LoadNextPlanet"",
                    ""type"": ""Button"",
                    ""id"": ""c6f44670-9ad6-400c-b590-d7383c01fff6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MiniMenu"",
                    ""type"": ""Button"",
                    ""id"": ""4cb82695-ff8b-4d06-9278-8c5e4eef1ed6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""83812f27-0ff5-4724-b06f-48594200a6cd"",
                    ""path"": ""<Keyboard>/o"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenLevelCompleteUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be804bf1-79d0-447b-aa7e-9f5c099ca487"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""OpenLevelCompleteUI"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9275bf79-c5ae-4f1c-b7f4-ab17205c2178"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadNextPlanet"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a41d8250-4df2-4cea-9379-f03f5924e98a"",
                    ""path"": ""<Keyboard>/ctrl"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8c26237d-f2fa-4826-8be0-23997c45d202"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8125e93-ecd0-4736-8dd3-56714afae38e"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b28bf9e2-f1ad-4b24-9b3b-2aaa4aee8a4d"",
                    ""path"": ""<Keyboard>/r"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Resume"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7710c767-b790-4a14-82a4-e6510480b742"",
                    ""path"": ""<Keyboard>/m"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LoadMainMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""88a808d2-1e74-4508-a443-3f0145adf5dc"",
                    ""path"": ""<Keyboard>/tab"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiniMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""64fba450-c2ae-4826-bd86-c3bd2da1b813"",
                    ""path"": ""<Gamepad>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MiniMenu"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""UIActions"",
            ""id"": ""94475e1e-50bd-40fb-84bb-a6e03404f335"",
            ""actions"": [
                {
                    ""name"": ""StartGame"",
                    ""type"": ""Button"",
                    ""id"": ""4d97b2ca-8be9-4e22-be5f-40b61d6cfe37"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayCinematic"",
                    ""type"": ""Button"",
                    ""id"": ""447e6ff1-0c55-4154-845f-22acd7f8881a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Controls"",
                    ""type"": ""Button"",
                    ""id"": ""3715612c-dace-4bb2-aa78-24ef7c7bd661"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Credits"",
                    ""type"": ""Button"",
                    ""id"": ""61455fbf-0693-47c0-8cdf-384696e64811"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Back"",
                    ""type"": ""Button"",
                    ""id"": ""4a3fb4d5-16af-4faa-a789-41761fde3771"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""KeyboardControls"",
                    ""type"": ""Button"",
                    ""id"": ""adff948e-1131-4950-b5db-2aee868b0425"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PlayStationControls"",
                    ""type"": ""Button"",
                    ""id"": ""d62e4890-4a87-4d53-8566-090299e5c68b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""XboxControls"",
                    ""type"": ""Button"",
                    ""id"": ""8852a90b-5ed3-48e6-951a-bad644adfab5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Mute"",
                    ""type"": ""Button"",
                    ""id"": ""98caf485-9edc-460e-839e-bf6da6aec2dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UnMute"",
                    ""type"": ""Button"",
                    ""id"": ""34cda2b7-c41a-4ac7-9903-76d0485b58a2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""QuitGame"",
                    ""type"": ""Button"",
                    ""id"": ""29608661-196f-4664-b429-d1cc0ed251d9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""e926c17f-3e87-4620-baa1-c24056a8ecc4"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bd14ca5b-f77b-4f45-ad21-7f7301860edf"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""66f3690e-94ed-479c-8097-368cde6a5a93"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayCinematic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d7a619a7-85e8-4916-b330-8d437ade9649"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayCinematic"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""c4e31bb2-ccfb-4c3e-a3c1-4c9e69155b32"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""843e348b-ef48-4f0e-aaf5-838ddea25bfa"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Controls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""03152725-7416-4171-b186-5bdaf81ed51d"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Credits"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5068b3b-6d87-415c-a524-0902a6abf280"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Credits"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62b0d516-345d-4a6a-989c-6f3698497fc1"",
                    ""path"": ""<Keyboard>/b"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Back"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""be170826-6423-4b47-9540-0236fb6c574e"",
                    ""path"": ""<Keyboard>/k"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardControls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ed615cd9-3923-440f-a8a3-7500b16a0672"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""KeyboardControls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e38be89-24d0-4396-97b4-a38efd18a8e4"",
                    ""path"": ""<Keyboard>/p"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayStationControls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cc873f6c-480d-4fe6-a228-f4a59b042e1d"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PlayStationControls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5b92d94f-6b2c-4854-96bb-39b77b841fc3"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XboxControls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f05ae2e5-162a-4def-afde-26f802c51d74"",
                    ""path"": ""<Keyboard>/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""XboxControls"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3ba58c8a-e134-4c1b-b7bc-447d6a823f7a"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbfdef33-8426-44af-a5a6-b8c6d4924016"",
                    ""path"": ""<Gamepad>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Mute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""098b02b6-bcf8-46c7-984f-572a3bbe2c14"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnMute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d90ded18-5796-4c1f-a019-ba4085359458"",
                    ""path"": ""<Gamepad>/dpad/left"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UnMute"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0b7cb38e-d164-429e-b31f-bbfd0a1cf3d9"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""QuitGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Profiler
        m_Profiler = asset.FindActionMap("Profiler", throwIfNotFound: true);
        m_Profiler_MoveKeys = m_Profiler.FindAction("MoveKeys", throwIfNotFound: true);
        m_Profiler_Jump = m_Profiler.FindAction("Jump", throwIfNotFound: true);
        m_Profiler_Attack = m_Profiler.FindAction("Attack", throwIfNotFound: true);
        m_Profiler_Look = m_Profiler.FindAction("Look", throwIfNotFound: true);
        m_Profiler_MoveController = m_Profiler.FindAction("MoveController", throwIfNotFound: true);
        m_Profiler_Dodge = m_Profiler.FindAction("Dodge", throwIfNotFound: true);
        m_Profiler_Shoot = m_Profiler.FindAction("Shoot", throwIfNotFound: true);
        m_Profiler_Unarmed = m_Profiler.FindAction("Unarmed", throwIfNotFound: true);
        m_Profiler_Skip = m_Profiler.FindAction("Skip", throwIfNotFound: true);
        m_Profiler_JetPack = m_Profiler.FindAction("JetPack", throwIfNotFound: true);
        m_Profiler_TalkArgyle = m_Profiler.FindAction("TalkArgyle", throwIfNotFound: true);
        m_Profiler_Pollinate = m_Profiler.FindAction("Pollinate", throwIfNotFound: true);
        m_Profiler_DialogueOptionOne = m_Profiler.FindAction("DialogueOptionOne", throwIfNotFound: true);
        m_Profiler_DialogueOptionTwo = m_Profiler.FindAction("DialogueOptionTwo", throwIfNotFound: true);
        m_Profiler_DialogueOptionThree = m_Profiler.FindAction("DialogueOptionThree", throwIfNotFound: true);
        m_Profiler_ActivateDialogue = m_Profiler.FindAction("ActivateDialogue", throwIfNotFound: true);
        m_Profiler_AskMoonbeam = m_Profiler.FindAction("AskMoonbeam", throwIfNotFound: true);
        m_Profiler_CloseDialogue = m_Profiler.FindAction("CloseDialogue", throwIfNotFound: true);
        // InGameUI
        m_InGameUI = asset.FindActionMap("InGameUI", throwIfNotFound: true);
        m_InGameUI_OpenLevelCompleteUI = m_InGameUI.FindAction("OpenLevelCompleteUI", throwIfNotFound: true);
        m_InGameUI_LoadMainMenu = m_InGameUI.FindAction("LoadMainMenu", throwIfNotFound: true);
        m_InGameUI_Resume = m_InGameUI.FindAction("Resume", throwIfNotFound: true);
        m_InGameUI_PauseGame = m_InGameUI.FindAction("PauseGame", throwIfNotFound: true);
        m_InGameUI_LoadNextPlanet = m_InGameUI.FindAction("LoadNextPlanet", throwIfNotFound: true);
        m_InGameUI_MiniMenu = m_InGameUI.FindAction("MiniMenu", throwIfNotFound: true);
        // UIActions
        m_UIActions = asset.FindActionMap("UIActions", throwIfNotFound: true);
        m_UIActions_StartGame = m_UIActions.FindAction("StartGame", throwIfNotFound: true);
        m_UIActions_PlayCinematic = m_UIActions.FindAction("PlayCinematic", throwIfNotFound: true);
        m_UIActions_Controls = m_UIActions.FindAction("Controls", throwIfNotFound: true);
        m_UIActions_Credits = m_UIActions.FindAction("Credits", throwIfNotFound: true);
        m_UIActions_Back = m_UIActions.FindAction("Back", throwIfNotFound: true);
        m_UIActions_KeyboardControls = m_UIActions.FindAction("KeyboardControls", throwIfNotFound: true);
        m_UIActions_PlayStationControls = m_UIActions.FindAction("PlayStationControls", throwIfNotFound: true);
        m_UIActions_XboxControls = m_UIActions.FindAction("XboxControls", throwIfNotFound: true);
        m_UIActions_Mute = m_UIActions.FindAction("Mute", throwIfNotFound: true);
        m_UIActions_UnMute = m_UIActions.FindAction("UnMute", throwIfNotFound: true);
        m_UIActions_QuitGame = m_UIActions.FindAction("QuitGame", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Profiler
    private readonly InputActionMap m_Profiler;
    private IProfilerActions m_ProfilerActionsCallbackInterface;
    private readonly InputAction m_Profiler_MoveKeys;
    private readonly InputAction m_Profiler_Jump;
    private readonly InputAction m_Profiler_Attack;
    private readonly InputAction m_Profiler_Look;
    private readonly InputAction m_Profiler_MoveController;
    private readonly InputAction m_Profiler_Dodge;
    private readonly InputAction m_Profiler_Shoot;
    private readonly InputAction m_Profiler_Unarmed;
    private readonly InputAction m_Profiler_Skip;
    private readonly InputAction m_Profiler_JetPack;
    private readonly InputAction m_Profiler_TalkArgyle;
    private readonly InputAction m_Profiler_Pollinate;
    private readonly InputAction m_Profiler_DialogueOptionOne;
    private readonly InputAction m_Profiler_DialogueOptionTwo;
    private readonly InputAction m_Profiler_DialogueOptionThree;
    private readonly InputAction m_Profiler_ActivateDialogue;
    private readonly InputAction m_Profiler_AskMoonbeam;
    private readonly InputAction m_Profiler_CloseDialogue;
    public struct ProfilerActions
    {
        private @InputProfiler m_Wrapper;
        public ProfilerActions(@InputProfiler wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveKeys => m_Wrapper.m_Profiler_MoveKeys;
        public InputAction @Jump => m_Wrapper.m_Profiler_Jump;
        public InputAction @Attack => m_Wrapper.m_Profiler_Attack;
        public InputAction @Look => m_Wrapper.m_Profiler_Look;
        public InputAction @MoveController => m_Wrapper.m_Profiler_MoveController;
        public InputAction @Dodge => m_Wrapper.m_Profiler_Dodge;
        public InputAction @Shoot => m_Wrapper.m_Profiler_Shoot;
        public InputAction @Unarmed => m_Wrapper.m_Profiler_Unarmed;
        public InputAction @Skip => m_Wrapper.m_Profiler_Skip;
        public InputAction @JetPack => m_Wrapper.m_Profiler_JetPack;
        public InputAction @TalkArgyle => m_Wrapper.m_Profiler_TalkArgyle;
        public InputAction @Pollinate => m_Wrapper.m_Profiler_Pollinate;
        public InputAction @DialogueOptionOne => m_Wrapper.m_Profiler_DialogueOptionOne;
        public InputAction @DialogueOptionTwo => m_Wrapper.m_Profiler_DialogueOptionTwo;
        public InputAction @DialogueOptionThree => m_Wrapper.m_Profiler_DialogueOptionThree;
        public InputAction @ActivateDialogue => m_Wrapper.m_Profiler_ActivateDialogue;
        public InputAction @AskMoonbeam => m_Wrapper.m_Profiler_AskMoonbeam;
        public InputAction @CloseDialogue => m_Wrapper.m_Profiler_CloseDialogue;
        public InputActionMap Get() { return m_Wrapper.m_Profiler; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(ProfilerActions set) { return set.Get(); }
        public void SetCallbacks(IProfilerActions instance)
        {
            if (m_Wrapper.m_ProfilerActionsCallbackInterface != null)
            {
                @MoveKeys.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveKeys;
                @MoveKeys.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveKeys;
                @MoveKeys.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveKeys;
                @Jump.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJump;
                @Jump.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJump;
                @Jump.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJump;
                @Attack.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAttack;
                @Attack.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAttack;
                @Attack.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAttack;
                @Look.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnLook;
                @Look.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnLook;
                @Look.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnLook;
                @MoveController.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveController;
                @MoveController.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveController;
                @MoveController.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnMoveController;
                @Dodge.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDodge;
                @Dodge.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDodge;
                @Dodge.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDodge;
                @Shoot.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnShoot;
                @Shoot.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnShoot;
                @Shoot.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnShoot;
                @Unarmed.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUnarmed;
                @Unarmed.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUnarmed;
                @Unarmed.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnUnarmed;
                @Skip.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnSkip;
                @Skip.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnSkip;
                @Skip.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnSkip;
                @JetPack.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJetPack;
                @JetPack.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJetPack;
                @JetPack.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnJetPack;
                @TalkArgyle.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTalkArgyle;
                @TalkArgyle.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTalkArgyle;
                @TalkArgyle.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnTalkArgyle;
                @Pollinate.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnPollinate;
                @Pollinate.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnPollinate;
                @Pollinate.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnPollinate;
                @DialogueOptionOne.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionOne;
                @DialogueOptionOne.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionOne;
                @DialogueOptionOne.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionOne;
                @DialogueOptionTwo.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionTwo;
                @DialogueOptionTwo.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionTwo;
                @DialogueOptionTwo.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionTwo;
                @DialogueOptionThree.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionThree;
                @DialogueOptionThree.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionThree;
                @DialogueOptionThree.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnDialogueOptionThree;
                @ActivateDialogue.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnActivateDialogue;
                @ActivateDialogue.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnActivateDialogue;
                @ActivateDialogue.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnActivateDialogue;
                @AskMoonbeam.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAskMoonbeam;
                @AskMoonbeam.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAskMoonbeam;
                @AskMoonbeam.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnAskMoonbeam;
                @CloseDialogue.started -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnCloseDialogue;
                @CloseDialogue.performed -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnCloseDialogue;
                @CloseDialogue.canceled -= m_Wrapper.m_ProfilerActionsCallbackInterface.OnCloseDialogue;
            }
            m_Wrapper.m_ProfilerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MoveKeys.started += instance.OnMoveKeys;
                @MoveKeys.performed += instance.OnMoveKeys;
                @MoveKeys.canceled += instance.OnMoveKeys;
                @Jump.started += instance.OnJump;
                @Jump.performed += instance.OnJump;
                @Jump.canceled += instance.OnJump;
                @Attack.started += instance.OnAttack;
                @Attack.performed += instance.OnAttack;
                @Attack.canceled += instance.OnAttack;
                @Look.started += instance.OnLook;
                @Look.performed += instance.OnLook;
                @Look.canceled += instance.OnLook;
                @MoveController.started += instance.OnMoveController;
                @MoveController.performed += instance.OnMoveController;
                @MoveController.canceled += instance.OnMoveController;
                @Dodge.started += instance.OnDodge;
                @Dodge.performed += instance.OnDodge;
                @Dodge.canceled += instance.OnDodge;
                @Shoot.started += instance.OnShoot;
                @Shoot.performed += instance.OnShoot;
                @Shoot.canceled += instance.OnShoot;
                @Unarmed.started += instance.OnUnarmed;
                @Unarmed.performed += instance.OnUnarmed;
                @Unarmed.canceled += instance.OnUnarmed;
                @Skip.started += instance.OnSkip;
                @Skip.performed += instance.OnSkip;
                @Skip.canceled += instance.OnSkip;
                @JetPack.started += instance.OnJetPack;
                @JetPack.performed += instance.OnJetPack;
                @JetPack.canceled += instance.OnJetPack;
                @TalkArgyle.started += instance.OnTalkArgyle;
                @TalkArgyle.performed += instance.OnTalkArgyle;
                @TalkArgyle.canceled += instance.OnTalkArgyle;
                @Pollinate.started += instance.OnPollinate;
                @Pollinate.performed += instance.OnPollinate;
                @Pollinate.canceled += instance.OnPollinate;
                @DialogueOptionOne.started += instance.OnDialogueOptionOne;
                @DialogueOptionOne.performed += instance.OnDialogueOptionOne;
                @DialogueOptionOne.canceled += instance.OnDialogueOptionOne;
                @DialogueOptionTwo.started += instance.OnDialogueOptionTwo;
                @DialogueOptionTwo.performed += instance.OnDialogueOptionTwo;
                @DialogueOptionTwo.canceled += instance.OnDialogueOptionTwo;
                @DialogueOptionThree.started += instance.OnDialogueOptionThree;
                @DialogueOptionThree.performed += instance.OnDialogueOptionThree;
                @DialogueOptionThree.canceled += instance.OnDialogueOptionThree;
                @ActivateDialogue.started += instance.OnActivateDialogue;
                @ActivateDialogue.performed += instance.OnActivateDialogue;
                @ActivateDialogue.canceled += instance.OnActivateDialogue;
                @AskMoonbeam.started += instance.OnAskMoonbeam;
                @AskMoonbeam.performed += instance.OnAskMoonbeam;
                @AskMoonbeam.canceled += instance.OnAskMoonbeam;
                @CloseDialogue.started += instance.OnCloseDialogue;
                @CloseDialogue.performed += instance.OnCloseDialogue;
                @CloseDialogue.canceled += instance.OnCloseDialogue;
            }
        }
    }
    public ProfilerActions @Profiler => new ProfilerActions(this);

    // InGameUI
    private readonly InputActionMap m_InGameUI;
    private IInGameUIActions m_InGameUIActionsCallbackInterface;
    private readonly InputAction m_InGameUI_OpenLevelCompleteUI;
    private readonly InputAction m_InGameUI_LoadMainMenu;
    private readonly InputAction m_InGameUI_Resume;
    private readonly InputAction m_InGameUI_PauseGame;
    private readonly InputAction m_InGameUI_LoadNextPlanet;
    private readonly InputAction m_InGameUI_MiniMenu;
    public struct InGameUIActions
    {
        private @InputProfiler m_Wrapper;
        public InGameUIActions(@InputProfiler wrapper) { m_Wrapper = wrapper; }
        public InputAction @OpenLevelCompleteUI => m_Wrapper.m_InGameUI_OpenLevelCompleteUI;
        public InputAction @LoadMainMenu => m_Wrapper.m_InGameUI_LoadMainMenu;
        public InputAction @Resume => m_Wrapper.m_InGameUI_Resume;
        public InputAction @PauseGame => m_Wrapper.m_InGameUI_PauseGame;
        public InputAction @LoadNextPlanet => m_Wrapper.m_InGameUI_LoadNextPlanet;
        public InputAction @MiniMenu => m_Wrapper.m_InGameUI_MiniMenu;
        public InputActionMap Get() { return m_Wrapper.m_InGameUI; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameUIActions set) { return set.Get(); }
        public void SetCallbacks(IInGameUIActions instance)
        {
            if (m_Wrapper.m_InGameUIActionsCallbackInterface != null)
            {
                @OpenLevelCompleteUI.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnOpenLevelCompleteUI;
                @OpenLevelCompleteUI.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnOpenLevelCompleteUI;
                @OpenLevelCompleteUI.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnOpenLevelCompleteUI;
                @LoadMainMenu.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadMainMenu;
                @LoadMainMenu.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadMainMenu;
                @LoadMainMenu.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadMainMenu;
                @Resume.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnResume;
                @Resume.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnResume;
                @Resume.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnResume;
                @PauseGame.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPauseGame;
                @PauseGame.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPauseGame;
                @PauseGame.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnPauseGame;
                @LoadNextPlanet.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadNextPlanet;
                @LoadNextPlanet.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadNextPlanet;
                @LoadNextPlanet.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnLoadNextPlanet;
                @MiniMenu.started -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnMiniMenu;
                @MiniMenu.performed -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnMiniMenu;
                @MiniMenu.canceled -= m_Wrapper.m_InGameUIActionsCallbackInterface.OnMiniMenu;
            }
            m_Wrapper.m_InGameUIActionsCallbackInterface = instance;
            if (instance != null)
            {
                @OpenLevelCompleteUI.started += instance.OnOpenLevelCompleteUI;
                @OpenLevelCompleteUI.performed += instance.OnOpenLevelCompleteUI;
                @OpenLevelCompleteUI.canceled += instance.OnOpenLevelCompleteUI;
                @LoadMainMenu.started += instance.OnLoadMainMenu;
                @LoadMainMenu.performed += instance.OnLoadMainMenu;
                @LoadMainMenu.canceled += instance.OnLoadMainMenu;
                @Resume.started += instance.OnResume;
                @Resume.performed += instance.OnResume;
                @Resume.canceled += instance.OnResume;
                @PauseGame.started += instance.OnPauseGame;
                @PauseGame.performed += instance.OnPauseGame;
                @PauseGame.canceled += instance.OnPauseGame;
                @LoadNextPlanet.started += instance.OnLoadNextPlanet;
                @LoadNextPlanet.performed += instance.OnLoadNextPlanet;
                @LoadNextPlanet.canceled += instance.OnLoadNextPlanet;
                @MiniMenu.started += instance.OnMiniMenu;
                @MiniMenu.performed += instance.OnMiniMenu;
                @MiniMenu.canceled += instance.OnMiniMenu;
            }
        }
    }
    public InGameUIActions @InGameUI => new InGameUIActions(this);

    // UIActions
    private readonly InputActionMap m_UIActions;
    private IUIActionsActions m_UIActionsActionsCallbackInterface;
    private readonly InputAction m_UIActions_StartGame;
    private readonly InputAction m_UIActions_PlayCinematic;
    private readonly InputAction m_UIActions_Controls;
    private readonly InputAction m_UIActions_Credits;
    private readonly InputAction m_UIActions_Back;
    private readonly InputAction m_UIActions_KeyboardControls;
    private readonly InputAction m_UIActions_PlayStationControls;
    private readonly InputAction m_UIActions_XboxControls;
    private readonly InputAction m_UIActions_Mute;
    private readonly InputAction m_UIActions_UnMute;
    private readonly InputAction m_UIActions_QuitGame;
    public struct UIActionsActions
    {
        private @InputProfiler m_Wrapper;
        public UIActionsActions(@InputProfiler wrapper) { m_Wrapper = wrapper; }
        public InputAction @StartGame => m_Wrapper.m_UIActions_StartGame;
        public InputAction @PlayCinematic => m_Wrapper.m_UIActions_PlayCinematic;
        public InputAction @Controls => m_Wrapper.m_UIActions_Controls;
        public InputAction @Credits => m_Wrapper.m_UIActions_Credits;
        public InputAction @Back => m_Wrapper.m_UIActions_Back;
        public InputAction @KeyboardControls => m_Wrapper.m_UIActions_KeyboardControls;
        public InputAction @PlayStationControls => m_Wrapper.m_UIActions_PlayStationControls;
        public InputAction @XboxControls => m_Wrapper.m_UIActions_XboxControls;
        public InputAction @Mute => m_Wrapper.m_UIActions_Mute;
        public InputAction @UnMute => m_Wrapper.m_UIActions_UnMute;
        public InputAction @QuitGame => m_Wrapper.m_UIActions_QuitGame;
        public InputActionMap Get() { return m_Wrapper.m_UIActions; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(UIActionsActions set) { return set.Get(); }
        public void SetCallbacks(IUIActionsActions instance)
        {
            if (m_Wrapper.m_UIActionsActionsCallbackInterface != null)
            {
                @StartGame.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnStartGame;
                @StartGame.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnStartGame;
                @StartGame.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnStartGame;
                @PlayCinematic.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayCinematic;
                @PlayCinematic.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayCinematic;
                @PlayCinematic.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayCinematic;
                @Controls.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnControls;
                @Controls.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnControls;
                @Controls.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnControls;
                @Credits.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnCredits;
                @Credits.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnCredits;
                @Credits.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnCredits;
                @Back.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnBack;
                @Back.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnBack;
                @Back.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnBack;
                @KeyboardControls.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnKeyboardControls;
                @KeyboardControls.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnKeyboardControls;
                @KeyboardControls.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnKeyboardControls;
                @PlayStationControls.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayStationControls;
                @PlayStationControls.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayStationControls;
                @PlayStationControls.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnPlayStationControls;
                @XboxControls.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnXboxControls;
                @XboxControls.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnXboxControls;
                @XboxControls.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnXboxControls;
                @Mute.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnMute;
                @Mute.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnMute;
                @Mute.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnMute;
                @UnMute.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnUnMute;
                @UnMute.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnUnMute;
                @UnMute.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnUnMute;
                @QuitGame.started -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnQuitGame;
                @QuitGame.performed -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnQuitGame;
                @QuitGame.canceled -= m_Wrapper.m_UIActionsActionsCallbackInterface.OnQuitGame;
            }
            m_Wrapper.m_UIActionsActionsCallbackInterface = instance;
            if (instance != null)
            {
                @StartGame.started += instance.OnStartGame;
                @StartGame.performed += instance.OnStartGame;
                @StartGame.canceled += instance.OnStartGame;
                @PlayCinematic.started += instance.OnPlayCinematic;
                @PlayCinematic.performed += instance.OnPlayCinematic;
                @PlayCinematic.canceled += instance.OnPlayCinematic;
                @Controls.started += instance.OnControls;
                @Controls.performed += instance.OnControls;
                @Controls.canceled += instance.OnControls;
                @Credits.started += instance.OnCredits;
                @Credits.performed += instance.OnCredits;
                @Credits.canceled += instance.OnCredits;
                @Back.started += instance.OnBack;
                @Back.performed += instance.OnBack;
                @Back.canceled += instance.OnBack;
                @KeyboardControls.started += instance.OnKeyboardControls;
                @KeyboardControls.performed += instance.OnKeyboardControls;
                @KeyboardControls.canceled += instance.OnKeyboardControls;
                @PlayStationControls.started += instance.OnPlayStationControls;
                @PlayStationControls.performed += instance.OnPlayStationControls;
                @PlayStationControls.canceled += instance.OnPlayStationControls;
                @XboxControls.started += instance.OnXboxControls;
                @XboxControls.performed += instance.OnXboxControls;
                @XboxControls.canceled += instance.OnXboxControls;
                @Mute.started += instance.OnMute;
                @Mute.performed += instance.OnMute;
                @Mute.canceled += instance.OnMute;
                @UnMute.started += instance.OnUnMute;
                @UnMute.performed += instance.OnUnMute;
                @UnMute.canceled += instance.OnUnMute;
                @QuitGame.started += instance.OnQuitGame;
                @QuitGame.performed += instance.OnQuitGame;
                @QuitGame.canceled += instance.OnQuitGame;
            }
        }
    }
    public UIActionsActions @UIActions => new UIActionsActions(this);
    public interface IProfilerActions
    {
        void OnMoveKeys(InputAction.CallbackContext context);
        void OnJump(InputAction.CallbackContext context);
        void OnAttack(InputAction.CallbackContext context);
        void OnLook(InputAction.CallbackContext context);
        void OnMoveController(InputAction.CallbackContext context);
        void OnDodge(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnUnarmed(InputAction.CallbackContext context);
        void OnSkip(InputAction.CallbackContext context);
        void OnJetPack(InputAction.CallbackContext context);
        void OnTalkArgyle(InputAction.CallbackContext context);
        void OnPollinate(InputAction.CallbackContext context);
        void OnDialogueOptionOne(InputAction.CallbackContext context);
        void OnDialogueOptionTwo(InputAction.CallbackContext context);
        void OnDialogueOptionThree(InputAction.CallbackContext context);
        void OnActivateDialogue(InputAction.CallbackContext context);
        void OnAskMoonbeam(InputAction.CallbackContext context);
        void OnCloseDialogue(InputAction.CallbackContext context);
    }
    public interface IInGameUIActions
    {
        void OnOpenLevelCompleteUI(InputAction.CallbackContext context);
        void OnLoadMainMenu(InputAction.CallbackContext context);
        void OnResume(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnLoadNextPlanet(InputAction.CallbackContext context);
        void OnMiniMenu(InputAction.CallbackContext context);
    }
    public interface IUIActionsActions
    {
        void OnStartGame(InputAction.CallbackContext context);
        void OnPlayCinematic(InputAction.CallbackContext context);
        void OnControls(InputAction.CallbackContext context);
        void OnCredits(InputAction.CallbackContext context);
        void OnBack(InputAction.CallbackContext context);
        void OnKeyboardControls(InputAction.CallbackContext context);
        void OnPlayStationControls(InputAction.CallbackContext context);
        void OnXboxControls(InputAction.CallbackContext context);
        void OnMute(InputAction.CallbackContext context);
        void OnUnMute(InputAction.CallbackContext context);
        void OnQuitGame(InputAction.CallbackContext context);
    }
}
